# Generated by Django 5.2.4 on 2025-08-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField()),
                ('extra_symptoms', models.TextField(blank=True, null=True)),
                ('predicted_disease', models.CharField(max_length=100)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
